./convert_cmyk_to_rgb.sh 10C_CMYK.jpg 10C.jpg
./convert_cmyk_to_rgb.sh 10D_CMYK.jpg 10D.jpg
./convert_cmyk_to_rgb.sh 10H_CMYK.jpg 10H.jpg
./convert_cmyk_to_rgb.sh 10S_CMYK.jpg 10S.jpg
./convert_cmyk_to_rgb.sh 2C_CMYK.jpg 2C.jpg
./convert_cmyk_to_rgb.sh 2D_CMYK.jpg 2D.jpg
./convert_cmyk_to_rgb.sh 2H_CMYK.jpg 2H.jpg
./convert_cmyk_to_rgb.sh 2S_CMYK.jpg 2S.jpg
./convert_cmyk_to_rgb.sh 3C_CMYK.jpg 3C.jpg
./convert_cmyk_to_rgb.sh 3D_CMYK.jpg 3D.jpg
./convert_cmyk_to_rgb.sh 3H_CMYK.jpg 3H.jpg
./convert_cmyk_to_rgb.sh 3S_CMYK.jpg 3S.jpg
./convert_cmyk_to_rgb.sh 4C_CMYK.jpg 4C.jpg
./convert_cmyk_to_rgb.sh 4D_CMYK.jpg 4D.jpg
./convert_cmyk_to_rgb.sh 4H_CMYK.jpg 4H.jpg
./convert_cmyk_to_rgb.sh 4S_CMYK.jpg 4S.jpg
./convert_cmyk_to_rgb.sh 5C_CMYK.jpg 5C.jpg
./convert_cmyk_to_rgb.sh 5D_CMYK.jpg 5D.jpg
./convert_cmyk_to_rgb.sh 5H_CMYK.jpg 5H.jpg
./convert_cmyk_to_rgb.sh 5S_CMYK.jpg 5S.jpg
./convert_cmyk_to_rgb.sh 6C_CMYK.jpg 6C.jpg
./convert_cmyk_to_rgb.sh 6D_CMYK.jpg 6D.jpg
./convert_cmyk_to_rgb.sh 6H_CMYK.jpg 6H.jpg
./convert_cmyk_to_rgb.sh 6S_CMYK.jpg 6S.jpg
./convert_cmyk_to_rgb.sh 7C_CMYK.jpg 7C.jpg
./convert_cmyk_to_rgb.sh 7D_CMYK.jpg 7D.jpg
./convert_cmyk_to_rgb.sh 7H_CMYK.jpg 7H.jpg
./convert_cmyk_to_rgb.sh 7S_CMYK.jpg 7S.jpg
./convert_cmyk_to_rgb.sh 8C_CMYK.jpg 8C.jpg
./convert_cmyk_to_rgb.sh 8D_CMYK.jpg 8D.jpg
./convert_cmyk_to_rgb.sh 8H_CMYK.jpg 8H.jpg
./convert_cmyk_to_rgb.sh 8S_CMYK.jpg 8S.jpg
./convert_cmyk_to_rgb.sh 9C_CMYK.jpg 9C.jpg
./convert_cmyk_to_rgb.sh 9D_CMYK.jpg 9D.jpg
./convert_cmyk_to_rgb.sh 9H_CMYK.jpg 9H.jpg
./convert_cmyk_to_rgb.sh 9S_CMYK.jpg 9S.jpg
./convert_cmyk_to_rgb.sh AC_CMYK.jpg AC.jpg
./convert_cmyk_to_rgb.sh AD_CMYK.jpg AD.jpg
./convert_cmyk_to_rgb.sh AH_CMYK.jpg AH.jpg
./convert_cmyk_to_rgb.sh AS_CMYK.jpg AS.jpg
./convert_cmyk_to_rgb.sh JC_CMYK.jpg JC.jpg
./convert_cmyk_to_rgb.sh JD_CMYK.jpg JD.jpg
./convert_cmyk_to_rgb.sh JH_CMYK.jpg JH.jpg
./convert_cmyk_to_rgb.sh JS_CMYK.jpg JS.jpg
./convert_cmyk_to_rgb.sh KC_CMYK.jpg KC.jpg
./convert_cmyk_to_rgb.sh KD_CMYK.jpg KD.jpg
./convert_cmyk_to_rgb.sh KH_CMYK.jpg KH.jpg
./convert_cmyk_to_rgb.sh KS_CMYK.jpg KS.jpg
./convert_cmyk_to_rgb.sh QC_CMYK.jpg QC.jpg
./convert_cmyk_to_rgb.sh QD_CMYK.jpg QD.jpg
./convert_cmyk_to_rgb.sh QH_CMYK.jpg QH.jpg
./convert_cmyk_to_rgb.sh QS_CMYK.jpg QS.jpg
